[package]
name = "reasonable"
version = "0.1.0"
authors = ["Gabe Fierro <gtfierro@cs.berkeley.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdf = "0.1.4"
fasthash = "0.4.0"
datafrog = "2.0.1"
