[package]
name = "reasonable"
version = "0.1.0"
authors = ["Gabe Fierro <gtfierro@cs.berkeley.edu>"]
edition = "2018"

[dependencies]
rdf = "0.1.4"
fasthash = "0.4.0"
datafrog = "2.0.1"
roaring = "0.5.2"
itertools = "0.8"
disjoint-sets = "0.4.2"

[profile.release]
debug = true
