[package]
name = "reasonable"
version = "0.1.7"
authors = ["Gabe Fierro <gtfierro@cs.berkeley.edu>"]
repository = "https://github.com/gtfierro/reasonable"
homepage = "https://brickschema.org/"
license-file = "LICENSE"
readme = "README.md"
description = "An OWL 2 RL reasoner with reasonable performance"
edition = "2018"

[lib]
name = "reasonable"
crate-type = ["cdylib", "lib"]

[features]
python-library = ["pyo3"]

[dependencies]
rdf = "0.1.4"
fasthash = "0.4.0"
datafrog = "2.0.1"
roaring = "0.5.2"
itertools = "0.8"
disjoint-sets = "0.4.2"
log = "0.4"
env_logger = "0.7.1"
anyhow = "1.0.26"

[dependencies.pyo3]
version = "0.9.0-alpha.1"
optional = true
features = ["extension-module"]

[dependencies.rusqlite]
git = "https://github.com/phiresky/rusqlite"
branch = "pr/loadable-extensions"
features = ["functions", "blob", "loadable_extension"]

[dev-dependencies.rusqlite]
git = "https://github.com/phiresky/rusqlite"
branch = "pr/loadable-extensions"
features = ["functions", "blob"]

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin14-clang"
ar = "x86_64-apple-darwin14-ar"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false

[profile.release]
debug = true
