name: Nightly Build
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:
    name: Nightly Build
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: cargo build --verbose
      - name: deploy release
        uses: WebFreak001/deploy-nightly@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
        with:
          upload_url: "https://uploads.github.com/repos/gtfierro/reasonable/releases/29427999/assets{?name,label}"
          release_id: 29427999 # same as above (id can just be taken out the upload_url, it's used to find old releases)
          asset_path: Brick.ttl # path to archive to upload
          asset_name: Brick.ttl # name to upload the release as, use $$ to insert date (YYYYMMDD) and 6 letter commit hash
          asset_content_type: application/x-turtle # required by GitHub API
          max_releases: 7 # optional, if there are more releases than this matching the asset_name, the oldest ones are going to be deleted
